# Week 1: Introduction to Python: Google Colab and Python Basics


---

# Google Colab, Jupyter Notebooks, and Markdown


## Google Colab

**Google Colab** (short for Colaboratory) is a cloud-based platform that provides an environment to write and execute Python code. It is built on top of Jupyter Notebooks and offers a similar interface.

- **Free Access to GPUs**: One of Colab's standout features is its free GPU access which is beneficial for resource-intensive tasks such as deep learning.
  
- **No Setup Required**: Users can run Python code directly in their browser without any setup.

- **Easy Sharing**: Notebooks can be shared just like Google Docs or Sheets. You can also comment on any part of the notebook.

- **Integration with Google Drive**: It saves your work directly to your Google Drive, can be shared with others, and accessed from any device.


## Jupyter Notebooks

**Jupyter Notebook** is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations, and narrative text. Jupyter supports over 40 programming languages, including Python.

- **Interactive Output**: Your code can produce rich, interactive outputs such as images, videos, and even interactive graphs.

- **Integration with Big Data Tools**: It integrates with big data tools like Apache Spark, making it powerful for handling large datasets.

- **Export Options**: You can convert your Jupyter Notebook into various formats such as PDF, Python file, HTML, etc.

## Markdown

**Markdown** is a lightweight markup language that you can use to add formatting elements to plaintext text documents. It was created to be easy to read and easy to write.

Read more here about [Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb)

In both Google Colab and Jupyter Notebooks, cells can be changed to Markdown to add formatted text, headers, links, lists, and more.

**Basic Markdown Syntax**:
- Headers:
  ```markdown
  # This is a header level 1
  ## This is a header level 2
  ### This is a header level 3
  ```

- Emphasis:
  ```markdown
  *italic* or _italic_
  **bold** or __bold__
  ```

- Lists:
  ```markdown
  - Item 1
  - Item 2
   - Item 2.1
  ```

  or

  ```markdown
  1. First item
  2. Second item
  ```

- Links:
  ```markdown
  [Google](https://www.google.com)
  ```

- Images:
  ```markdown
  ![Alt text](URL_to_image)
  ```

- Code:
  Use single back-ticks (`) for inline code and triple back-ticks (```) for blocks of code.

- Blockquotes:
  ```markdown
  > This is a blockquote.
  ```

---
# Introduction to Python

Python, in the modern era of data-driven research, has emerged as one of the most preferred tools for data analysis, simulation, and modeling. Its versatility, combined with a vast array of libraries (modules), offers a robust platform for graduate-level research in numerous disciplines.



## A Brief History of Python
- Created by Guido van Rossum and first released in 1991.
- Designed for readability and ease of use with its distinct use of whitespace and straightforward syntax.
- Rapidly adopted in scientific computing and data science due to extensive libraries and community support.



## Advantages of using Python in Policy analysis and data science
1. **Versatility**: Python is a general-purpose language, which means it can be used for web development, automation, scientific modeling, and more, in addition to data analysis.
2. **Extensive Libraries**: Modules like Pandas, NumPy, and SciPy provide ready-to-use functions for complex mathematical operations essential in policy analysis.
3. **Open-Source Nature**: Being open-source, Python encourages collaboration. Researchers and professionals worldwide contribute to its expanding set of libraries.
4. **Interactivity**: Tools like Jupyter Notebooks and Google Colab offer an interactive environment that's excellent for experimentation, visualization, and sharing of insights.
5. **Integration Capabilities**: Python can easily integrate with other languages like C, Java, and FORTRAN, providing more extensive functionality when needed.
6. **Strong Community Support**: Challenges faced during research or analysis can often be addressed with help from the global Python community through forums, webinars, and conferences.



## Disadvantages of using Python in Policy analysis and data science

1. **Performance**: Being an interpreted language, Python might be slower than compiled languages like C++ or Java. However, for most data analysis tasks, this difference is often negligible.
2. **Memory Consumption**: Python's simplicity sometimes leads to it consuming more memory, which can be a concern with extremely large datasets.
3. **Learning Curve for Advanced Libraries**: While Python itself is easy to pick up, some libraries essential for advanced data analysis might have a steep learning curve.
4. **Multithreading Limitations**: The Global Interpreter Lock (GIL) in Python means that only one thread can be executed at a time, potentially limiting tasks that require multi-threading.
5. **Maturity of Some Libraries**: While popular libraries like Pandas and NumPy are well-maintained, some niche libraries might lack comprehensive documentation or updates.





---
# Python Basics


## Variable definition & types

In Python, variables are dynamically typed, meaning you don't need to declare their type explicitly.


In [ ]:
# String type variable
class_topic = "Agricultural Policy Analysis"
# Integer type variable
participants = 6
# Floating point variable
average_duration_hours = 2.5
# Boolean
is_complicated = True
# List type variable: Contains multiple items in an ordered sequence
topics_covered = ["Python basics", "Git", "Policy analysis", "Time series"]
next_year_participants = participants + 3

Now that we have defined our variables lets use them:

In [ ]:
# Printing variables
print("The topic of this class is:", class_topic)
print("Number of participants:", participants)
print("Expected participants next year:", next_year_participants)
print("Average duration of each class (in hours):", average_duration_hours)
print("Topics to be covered include:", ', '.join(topics_covered))
print("")
# String formatting: A more advanced way of printing
print(f"In the research topic '{class_topic}', there are currently {participants} participants. \n"
"We expect this number to rise to {next_year_participants} next year.")

The topic of this class is: Agricultural Policy Analysis
Number of participants: 6
Expected participants next year: 9
Average duration of each class (in hours): 2.5
Topics to be covered include: Python basics, Git, Policy analysis, Time series

In the research topic 'Agricultural Policy Analysis', there are currently 6 participants. 
We expect this number to rise to {next_year_participants} next year.


In [ ]:
print(topics_covered)

['Python basics', 'Git', 'Policy analysis', 'Time series']



## What is 0-based Indexing?

In Python, sequences (like strings, lists, and tuples) use 0-based indexing. This means that the first element is accessed with the index `0`, the second element with index `1`, the third with index `2`, and so on.

### Why 0-based Indexing?

There isn't a universally accepted reason for why many languages use 0-based indexing, but there are a few logical reasons often cited:

1. **Historical Reason**: In some early programming, addressing memory locations directly was common, and the first location in memory was often denoted with a `0`.

2. **Mathematical Convenience**: When calculating offsets, 0-based indexing can simplify math. If the first element starts at 0, then an element at index `n` would be found `n` units away. This straightforward offset system is mathematically neat.

3. **Inclusive Range Operations**: When slicing in Python (and other 0-indexed languages), the beginning index is inclusive, and the end index is exclusive. This design often makes operations more straightforward. For example, the slice `[0:3]` will give elements at indices `0, 1, and 2`.

### Examples and Illustration:

Consider a list:
```python
fruits = ["apple", "banana", "cherry", "date"]
```

Visualizing the indexing:
```
  fruits    apple     banana    cherry     date
  index       0          1          2         3
```

- To access "apple", you'd write `fruits[0]`.
- To access "banana", you'd write `fruits[1]`.
- And so on.

### Common Confusions and Errors:

1. **Off-by-One Errors**: One of the most common mistakes, especially for beginners, is attempting to access the nth element using `n` as the index, rather than `n-1`. For instance, trying to access the third item in our `fruits` list using `fruits[3]` would give "date" instead of "cherry".

2. **Negative Indexing**: Python also supports negative indexing, which might seem counterintuitive at first but is quite powerful. An index of `-1` refers to the last element, `-2` refers to the second-to-last, and so on. In our example, `fruits[-1]` would return "date".


## Lists in Python

In Python, a list is an ordered collection of items. These items can be of any type, and a single list can contain items of mixed types. Lists are defined by enclosing the items (elements) in square brackets `[]`.

### Creating a List

```python
# A list of integers
numbers = [1, 2, 3, 4, 5]

# A list of strings
fruits = ["apple", "banana", "cherry"]

# A mixed list
mixed = [1, "apple", 3.5, True]
```

### Accessing List Elements

Python lists are zero-indexed, which means the first element is accessed with `0`, the second with `1`, and so on.

In [ ]:
fruits = ["apple", "banana", "cherry"]

# Accessing the first element
print(fruits[0])  # Outputs: apple

# Accessing the last element
print(fruits[-1])  # Outputs: cherry

apple
banana



### Modifying a List

Lists are mutable, meaning their elements can be changed after the list is created.

```python
fruits = ["apple", "banana", "cherry"]
fruits[1] = "blueberry"
print(fruits)  # Outputs: ['apple', 'blueberry', 'cherry']
```

### List Operations

- **Appending to a list**:
  ```python
  fruits.append("date")
  ```
After this operation, the "date" will be added to the end of the fruits list.

- **Inserting into a list**:
  ```python
  fruits.insert(1, "kiwi")
  ```
  With this, "kiwi" will be added to the fruits list at position 1, pushing all subsequent elements one position further.

- **Removing from a list**:
  ```python
  fruits.remove("apple")
  ```
After this operation, the first occurrence of "apple" will be removed from the fruits list.

- **Popping elements**:
  ```python
  last_fruit = fruits.pop()
  ```
In this case, the last item of the fruits list will be removed and its value will be stored in the last_fruit variable. If you wanted to pop an element from a specific index, you could use fruits.pop(index).

### Slicing Lists

You can extract portions of a list using slicing.




In [ ]:
numbers = [0, 1, 2, 3, 4, 5, 6]

# Get the first three elements
first_three = numbers[0:3]
print(first_three)  # Outputs: [0, 1, 2]

# Get elements from the third to the end of the list
from_third = numbers[2:]
print(from_third)  # Outputs: [2, 3, 4, 5, 6]

[0, 1, 2]
[0, 1]


### List Methods

Lists in Python have a variety of useful methods:

- `append()`: Adds an item to the end of the list.
- `extend()`: Appends the contents of a sequence to the list.
- `insert()`: Inserts an item at a given position.
- `remove()`: Removes the first occurrence of a value.
- `pop()`: Removes and returns the item at a given position.
- `index()`: Returns the index of the first matched item.
- `count()`: Returns the number of times an item appears in the list.
- `sort()`: Sorts the items.
- `reverse()`: Reverses the order of items.

### List Comprehensions (see subsequent lectures)

## Explanation of `.join()`

1. **Basic Definition**:
   The `.join()` method takes an iterable (like a list or tuple) of strings and concatenates its items into a single string using the string on which it was called as a delimiter.

2. **Example**:

   ```python
   delimiter = ", "
   words = ["apple", "banana", "cherry"]
   result = delimiter.join(words)
   print(result)  # Outputs: apple, banana, cherry
   ```

   In the example above, the string `", "` is our delimiter, and the `.join()` method is called on this delimiter. The elements of the `words` list are then concatenated into a single string with our delimiter between each item.

3. **Usage in your code**:
   
   When you have the line:
   ```python
   topics_covered = ["Crop Analysis", "Soil Health", "Irrigation Methods"]
   print("Topics to be covered include:", ', '.join(topics_covered))
   ```
   
   Here, `', '.join(topics_covered)` concatenates the strings in the `topics_covered` list into a single string. Each string in the list is separated by the delimiter `', '`. Thus, it produces the output:
   ```
   Topics to be covered include: Crop Analysis, Soil Health, Irrigation Methods
   ```

4. **Benefits**:

   Using `.join()` is often preferred over string concatenation using the `+` operator because:

   - It's more efficient, especially for joining a large number of strings.
   - It leads to cleaner and more readable code, especially when dealing with multiple items.


## What is an f-string?

In Python, starting from version 3.6, f-strings, also known as "formatted string literals," were introduced as a new way to embed expressions inside string literals. The letter "f" preceding a string denotes that it's an f-string.

### Why use f-strings?

F-strings provide a concise and convenient way to embed Python expressions inside string literals for formatting. They allow you to incorporate variables or expressions directly into strings without explicitly converting them or using concatenation.

### How does it work?

1. **Basic Usage**:
   An f-string is created by prefixing the string with the letter `f` or `F`. Inside this string, you can include variables or expressions within `{}` braces.
   
   ```python
   name = "Alice"
   age = 25
   print(f"{name} is {age} years old.")
   ```

   Output:
   ```
   Alice is 25 years old.
   ```

2. **Expressions within f-strings**:
   You can perform operations or call functions within the curly braces.
   
   ```python
   x = 5
   y = 10
   print(f"The sum of {x} and {y} is {x+y}.")
   ```

   Output:
   ```
   The sum of 5 and 10 is 15.
   ```

3. **Specifying Formats**:
   You can format the data inside the curly braces. For instance, formatting a number to 2 decimal places:
   
   ```python
   pi = 3.14159265359
   print(f"The value of pi rounded to two decimal places is {pi:.2f}.")
   ```

   Output:
   ```
   The value of pi rounded to two decimal places is 3.14.
   ```

---

## What are Booleans?

Booleans represent one of two values: `True` or `False`. Named after George Boole, a 19th-century mathematician who introduced Boolean algebra, they provide a way to represent truth values (true or false) in logic and computing.

### Basic Usage in Python:

In Python, the boolean type is represented by two keywords: `True` and `False` (note the capitalization).

```python
isRaining = False
isSunny = True
```

### Operations with Booleans:

1. **Comparison Operators**: These return Boolean values.
   - `==`: Equal to
   - `!=`: Not equal to
   - `<`: Less than
   - `<=`: Less than or equal to
   - `>`: Greater than
   - `>=`: Greater than or equal to

   Example:
   ```python
   x = 5
   y = 10
   print(x > y)  # Outputs: False
   ```

2. **Logical Operators**: These operate on Boolean values and return Boolean results.
   - `and`: Returns `True` if both operands are `True`.
   - `or`: Returns `True` if at least one of the operands is `True`.
   - `not`: Returns the opposite of the operand.

   Example:
   ```python
   isWeekend = True
   isHoliday = False
   print(isWeekend and isHoliday)  # Outputs: False
   print(isWeekend or isHoliday)   # Outputs: True
   print(not isWeekend)            # Outputs: False
   ```
---

## Logical statements

## What is it?

Logical statements in Python are essential for decision-making in your code.  The primary logical statements are `if`, `elif`, and `else`. These statements help in conditionally executing code depending on the result of a logical expression.

## How does ut work?

If statements evaluate an expression to yield a Boolean value: `True` or `False` and then takes an action based on the result. The syntax for an if statement is:

Lets break it down:

### 1. Boolean Values

In Python, the two Boolean values are `True` and `False`. They are used to represent the truthiness or falseness of an expression. Remember that they are case-sensitive.

In [ ]:
is_happy = True
is_sad = False
print(is_happy)

### 2. Comparison Operators

Comparison operators evaluate expressions to produce a Boolean result. The most common ones include:

- `==`: Equal to
- `!=`: Not equal to
- `<`: Less than
- `>`: Greater than
- `<=`: Less than or equal to
- `>=`: Greater than or equal to

In [ ]:
x = 5
y = 10
result = x < y
print(result)

### 3. Logical Operators

Python includes three main logical operators:

- `and`: Both conditions must be true
- `or`: At least one condition must be true
- `not`: Inverts the Boolean value

In [ ]:
is_tall = True
is_smart = False
result_and = is_tall and is_smart
print(result_and)
result_or = is_tall or is_smart
print(result_or)
result_not = not is_smart
print(result_not)

### 4. `if` Statement

The `if` statement runs a block of code only if the condition is true. Note the indentation. The code that is indented after the `if` statement is the code that will be executed if the condition is true. If the condition is false, the code will not be executed.

In [ ]:
if is_tall:
    print("You are tall!")

### 5. `elif` and `else` Statements

The `elif` (short for "else if") and `else` statements are used for handling additional conditions.

In [ ]:
if is_tall and is_smart:
    print("You are tall and smart!")
elif is_smart:
    print("You are smart!")
elif is_tall:
    print("You are tall!")
else:
    print("You are unique!")


## 6. Nested Conditional Statements

You can nest `if` statements within other `if` statements for more complex conditions. Note the indentation. The code that is indented after the `if` statement is the code that will be executed if the condition is true. If the condition is false, the code will not be executed.

In [ ]:
if is_tall:
    if is_smart:
        print("You are tall and smart!")
    else:
        print("You are tall!")

---
# Python Math

## Basic Math

Here is a couple of examples of doing basic math in Python.

1. **Addition**:
```python
a = 5
b = 3
sum_ = a + b
print(sum_)  # Outputs: 8
```

2. **Subtraction**:
```python
difference = a - b
print(difference)  # Outputs: 2
```

3. **Multiplication**:
```python
product = a * b
print(product)  # Outputs: 15
```

4. **Division**:
```python
quotient = a / b
print(quotient)  # Outputs: 1.6666666666666667
```

5. **Floor Division (Integer Division)**:
```python
floor_quotient = a // b
print(floor_quotient)  # Outputs: 1 (because it rounds down)
```

8. **Exponentiation**:
```python
squared = a**2
print(squared)  # Outputs: 25
```



## Advanced Math: NumPy

NumPy, which stands for Numerical Python, is a foundational package for numerical computations in Python. It provides support for arrays (including matrices) and offers a rich set of mathematical functions to operate on these arrays.

```python
import numpy as np
```

### Array Creation

You can create a NumPy array from a regular Python list or tuple using the `array` function.



In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]




### Basic Mathematical Operations

With NumPy, mathematical operations on arrays become straightforward. For example:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
print(a + b)

# Multiplication
print(a * b)

[5 7 9]
[ 4 10 18]


### Aggregation Functions

NumPy provides several aggregation functions.



In [ ]:
c = np.array([2, 8, 1, 5, 6])

# Find the maximum
print(np.max(c))

# Find the average
print(np.mean(c))

8
4.4


### Broadcasting

NumPy allows for broadcasting, which lets you perform operations on arrays of different shapes.



In [ ]:
d = np.array([[1, 2], [3, 4]])
e = np.array([1, 2])

print(d + e)

[[2 4]
 [4 6]]




### Indexing and Slicing

Just like Python lists, you can index and slice NumPy arrays.



In [ ]:
list_of_numbers = p.array(n[0, 1, 2, 3, 4, 5])

# Get the element at index 2
print(list_of_numbers[2])

# Get elements from index 2 to 4
print(list_of_numbers[2:5])

2
[2 3 4]


---

## Getting help about functions

To get help about a function, you can use the `help` function.

In [6]:
help(np.mean)

Help on _ArrayFunctionDispatcher in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computin

---

# Tutorial 1

Navigate to Google Colab and do the following:

- Create a new Jupyter notebook
- Rename it to \<your_name>\<Lecture_1_Tutorial>
- Share with me: jan5020@gmail.com

Please use the appropriate Markdown code to structure your tutorial solutions and use codeblocks to generate your answers.

1. Please use variables, `print`, f-strings, Booleans and other functions that you have learned to answer the following questions regarding yourself:
- Where were you born?
- How old are you now?
- How old will you be in 5 years?
- Create a list that contains your three favorite foods in decreasing order of preference.
 - Print the list using the `.join()` function.
 - What is your second favorite food?
 - What is your first and second favorite food?
 - Add a fourth favorite food to the list and print the updated list.
 - Replace your third favorite food with something else

2. Given that a = True, b = False, c = True. Evaluate the following:

  - a and b
  - a or b
  - not a
  - b or not a
  - a and c or not b
  - not b and not c
  - a and (b or c)

3. Given that `x = 12` and `y = 5`, do the following using basic Python math:
- What is the sum of x and y?
- Calculate the average.
- What the solution to x-squared minus y squared?

4. Create a array of numbers called `vars_list` that contain the following 10 numbers: 17,30,41,14,39,7,21,7,20,7. Using numpy please answer following:
- What is the sum of all of the numbers?
- Calculate the mean and median
- What is the standard deviation?
- Please extract all of the odd numers from the array

5. Create a 2x2 matrix and multiply it with another 2x2 matrix using NumPy.



